/*
 * File: app/store/Employees.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Employees', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.store.override.Employees',
        'MyApp.model.Employee'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Employee',
        storeId: 'Employees',
        listeners: [
            {
                fn: 'onStoreAddrecords',
                event: 'addrecords'
            }
        ],
        proxy: {
            type: 'localstorage'
        }
    },

    onStoreAddrecords: function(store, records, eOpts) {
        console.log("Employees store is synced yo");
    }

});