/*
 * File: app/store/Orders.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Orders', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.store.override.Orders',
        'MyApp.model.Order'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Order',
        storeId: 'Orders',
        proxy: {
            type: 'localstorage'
        },
        listeners: [
            {
                fn: 'onStoreRemoverecords',
                event: 'removerecords'
            },
            {
                fn: 'onStoreAddrecords',
                event: 'addrecords'
            },
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ]
    },

    onStoreRemoverecords: function(store, records, indices, eOpts) {
        console.log('orders remove event');
    },

    onStoreAddrecords: function(store, records, eOpts) {
        console.log('order add event');
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        console.log('order store load', records);

        //MyApp.app.getController('Home').loadStore(store);
    }

});