/*
 * File: app/store/Rolls.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Rolls', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.store.override.Rolls',
        'MyApp.model.Roll'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        model: 'MyApp.model.Roll',
        storeId: 'Rolls',
        listeners: [
            {
                fn: 'onStoreRemoverecords',
                event: 'removerecords'
            },
            {
                fn: 'onStoreAddrecords',
                event: 'addrecords'
            }
        ],
        proxy: {
            type: 'localstorage'
        }
    },

    onStoreRemoverecords: function(store, records, indices, eOpts) {
        console.log('remove roll event');
        //store.sync();
    },

    onStoreAddrecords: function(store, records, eOpts) {
        console.log('add roll event');
        //store.sync();
    }

});