/*
 * File: app/store/Windows_has_Rolls.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Windows_has_Rolls', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Window_has_Roll'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Window_has_Roll',
        storeId: 'Windows_has_Rolls',
        grouper: {
            groupFn: function(record) {
                return record.get('Roll_id');
            }
        },
        listeners: [
            {
                fn: 'onStoreAddrecords',
                event: 'addrecords'
            },
            {
                fn: 'onStoreRemoverecords',
                event: 'removerecords'
            }
        ],
        proxy: {
            type: 'localstorage'
        }
    },

    onStoreAddrecords: function(store, records, eOpts) {
        console.log('add whr event');
        store.sync();
    },

    onStoreRemoverecords: function(store, records, indices, eOpts) {
        console.log('remove whr event');
        store.sync();
    }

});