/*
 * File: app/store/Windows.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Windows', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.store.override.Windows',
        'MyApp.model.Window'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        groupField: 'Type',
        model: 'MyApp.model.Window',
        storeId: 'Windows',
        listeners: [
            {
                fn: 'onStoreRemoverecords',
                event: 'removerecords'
            },
            {
                fn: 'onStoreAddrecords',
                event: 'addrecords'
            }
        ],
        proxy: {
            type: 'localstorage'
        }
    },

    onStoreRemoverecords: function(store, records, indices, eOpts) {
        console.log('remove window event', records);
        store.sync();
    },

    onStoreAddrecords: function(store, records, eOpts) {
        console.log('add window event');
        store.sync();
    }

});