/*
 * File: app/store/Windows.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Windows', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.store.override.Windows',
        'MyApp.model.Window'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Window',
        storeId: 'Windows',
        listeners: [
            {
                fn: 'onStoreDeleteRecords',
                event: 'removerecords'
            },
            {
                fn: 'onStoreAddRecords',
                event: 'addrecords'
            },
            {
                fn: 'onStoreBeforeSync',
                event: 'beforesync'
            },
            {
                fn: 'onStoreLoad',
                event: 'load'
            }
        ],
        proxy: {
            type: 'localstorage'
        }
    },

    onStoreDeleteRecords: function(store, records, indices, eOpts) {
        //MyApp.app.getController('Inventory').reserveFilm2(records, 'delete');
        console.log('remove window record', records);
    },

    onStoreAddRecords: function(store, records, eOpts) {
        console.log('add window event');
        //MyApp.app.getController('Inventory').reserveFilm2(records, 'add');
    },

    onStoreBeforeSync: function(options, eOpts) {
        console.log('window store sync');
    },

    onStoreLoad: function(store, records, successful, operation, eOpts) {
        console.log('windowstore load');
    }

});