/*
 * File: app/view/Employees.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Employees', {
    extend: 'Ext.Container',
    alias: 'widget.employees',

    requires: [
        'MyApp.view.override.Employees'
    ],

    config: {
        id: 'employees',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'list',
                id: 'EmployeeList',
                itemTpl: [
                    '<div><img src="images/""{PicUrl}" />Order {Number} was created on {Created:date("m-d H:i:s")}</div>'
                ],
                store: 'Employees',
                infinite: true,
                onItemDisclosure: true,
                pinHeaders: false
            },
            {
                xtype: 'formpanel',
                id: 'EmployeeForm',
                items: [
                    {
                        xtype: 'container',
                        layout: {
                            type: 'hbox'
                        },
                        items: [
                            {
                                xtype: 'fieldset',
                                flex: 1,
                                width: '45%',
                                title: '',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        name: 'First',
                                        required: true,
                                        placeHolder: 'First Name'
                                    },
                                    {
                                        xtype: 'textfield',
                                        name: 'Last',
                                        placeHolder: 'Last Name'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                items: [
                                    {
                                        xtype: 'image',
                                        centered: false,
                                        height: '80px',
                                        id: 'EmployeePic',
                                        margin: '10px auto 10px auto',
                                        width: '80px',
                                        src: 'images'
                                    },
                                    {
                                        xtype: 'fileupload',
                                        autoUpload: false,
                                        url: 'php/getfile.php',
                                        border: '1px solid black',
                                        centered: false,
                                        cls: 'btn x-button',
                                        height: 22,
                                        hidden: false,
                                        id: 'fileBtn',
                                        itemId: 'fileBtn',
                                        margin: 'auto',
                                        width: 100
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        items: [
                            {
                                xtype: 'numberfield',
                                name: 'Phone',
                                required: true,
                                placeHolder: 'Phone Number'
                            },
                            {
                                xtype: 'emailfield',
                                name: 'Email',
                                placeHolder: 'Email'
                            },
                            {
                                xtype: 'textfield',
                                name: 'Street',
                                placeHolder: 'Street'
                            },
                            {
                                xtype: 'textfield',
                                name: 'City',
                                placeHolder: 'City'
                            },
                            {
                                xtype: 'selectfield',
                                name: 'State',
                                placeHolder: 'State',
                                options: [
                                    {
                                        text: 'State',
                                        value: ''
                                    },
                                    {
                                        text: 'Alabama',
                                        value: 'Alabama'
                                    },
                                    {
                                        text: 'Alaska',
                                        value: 'Alaska'
                                    },
                                    {
                                        text: 'Arizona',
                                        value: 'Arizona'
                                    },
                                    {
                                        text: 'Arkansas',
                                        value: 'Arkansas'
                                    },
                                    {
                                        text: 'California',
                                        value: 'California'
                                    },
                                    {
                                        text: 'Colorado',
                                        value: 'Colorado'
                                    },
                                    {
                                        text: 'Connecticut',
                                        value: 'Connecticut'
                                    },
                                    {
                                        text: 'Delaware',
                                        value: 'Delaware'
                                    },
                                    {
                                        text: 'Florida',
                                        value: 'Florida'
                                    },
                                    {
                                        text: 'Georgia',
                                        value: 'Georgia'
                                    },
                                    {
                                        text: 'Hawaii',
                                        value: 'Hawaii'
                                    },
                                    {
                                        text: 'Idaho',
                                        value: 'Idaho'
                                    },
                                    {
                                        text: 'Illinois',
                                        value: 'Illinois'
                                    },
                                    {
                                        text: 'Indiana',
                                        value: 'Indiana'
                                    },
                                    {
                                        text: 'Iowa',
                                        value: 'Iowa'
                                    },
                                    {
                                        text: 'Kansas',
                                        value: 'Kansas'
                                    },
                                    {
                                        text: 'Kentucky',
                                        value: 'Kentucky'
                                    },
                                    {
                                        text: 'Louisiana',
                                        value: 'Louisiana'
                                    },
                                    {
                                        text: 'Maine',
                                        value: 'Maine'
                                    },
                                    {
                                        text: 'Maryland',
                                        value: 'Maryland'
                                    },
                                    {
                                        text: 'Massachusetts',
                                        value: 'Massachusetts'
                                    },
                                    {
                                        text: 'Michigan',
                                        value: 'Michigan'
                                    },
                                    {
                                        text: 'Minnesota',
                                        value: 'Minnesota'
                                    },
                                    {
                                        text: 'Mississippi',
                                        value: 'Mississippi'
                                    },
                                    {
                                        text: 'Missouri',
                                        value: 'Missouri'
                                    },
                                    {
                                        text: 'Montana',
                                        value: 'Montana'
                                    },
                                    {
                                        text: 'Nebraska',
                                        value: 'Nebraska'
                                    },
                                    {
                                        text: 'Nevada',
                                        value: 'Nevada'
                                    },
                                    {
                                        text: 'New Hampshire',
                                        value: 'New Hampshire'
                                    },
                                    {
                                        text: 'New Jersey',
                                        value: 'New Jersey'
                                    },
                                    {
                                        text: 'New Mexico',
                                        value: 'New Mexico'
                                    },
                                    {
                                        text: 'New York',
                                        value: 'New York'
                                    },
                                    {
                                        text: 'North Carolina',
                                        value: 'North Carolina'
                                    },
                                    {
                                        text: 'North Dakota',
                                        value: 'North Dakota'
                                    },
                                    {
                                        text: 'Ohio',
                                        value: 'Ohio'
                                    },
                                    {
                                        text: 'Oklahoma',
                                        value: 'Oklahoma'
                                    },
                                    {
                                        text: 'Oregon',
                                        value: 'Oregon'
                                    },
                                    {
                                        text: 'Pennsylvania',
                                        value: 'Pennsylvania'
                                    },
                                    {
                                        text: 'Rhode Island',
                                        value: 'Rhode Island'
                                    },
                                    {
                                        text: 'South Carolina',
                                        value: 'South Carolina'
                                    },
                                    {
                                        text: 'South Dakota',
                                        value: 'South Dakota'
                                    },
                                    {
                                        text: 'Tennessee',
                                        value: 'Tennessee'
                                    },
                                    {
                                        text: 'Texas',
                                        value: 'Texas'
                                    },
                                    {
                                        text: 'Utah',
                                        value: 'Utah'
                                    },
                                    {
                                        text: 'Vermont',
                                        value: 'Vermont'
                                    },
                                    {
                                        text: 'Virginia',
                                        value: 'Virginia'
                                    },
                                    {
                                        text: 'Washington',
                                        value: 'Washington'
                                    },
                                    {
                                        text: 'West Virginia',
                                        value: 'West Virginia'
                                    },
                                    {
                                        text: 'Wisconsin',
                                        value: 'Wisconsin'
                                    },
                                    {
                                        text: 'Wyoming',
                                        value: 'Wyoming'
                                    }
                                ]
                            },
                            {
                                xtype: 'numberfield',
                                name: 'Zip',
                                placeHolder: 'Zip'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        cls: 'btn',
                        id: 'EnterEmployeeBtn',
                        text: 'Add'
                    }
                ]
            }
        ]
    }

});