/*
 * File: app/view/Home.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Home', {
    extend: 'Ext.Container',
    alias: 'widget.home',

    config: {
        cls: 'test',
        id: 'HomePanel',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'dataview',
                centered: false,
                id: 'HomeDataView',
                itemTpl: [
                    '<div class="homedataview" id=dv{#}>',
                    '    <p>{#}Order number: {name} </p>',
                    '    <p><span>Created on: {Created:date("m-d H:i:s")}</span></p>',
                    '</div>'
                ],
                useComponents: false
            }
        ]
    }

});