/*
 * File: app/view/Inventory.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Inventory', {
    extend: 'Ext.Container',
    alias: 'widget.inventory',

    config: {
        id: 'inventory',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'list',
                id: 'InventoryList',
                itemCls: 'tweet',
                itemTpl: [
                    '<div>{Manufacturer} {Type} {Shade}{Size}{RollNumber}{LinearFeet}<div class="deleteplaceholder"></div> </div>'
                ],
                store: 'Rolls',
                itemHeight: 40,
                onItemDisclosure: true,
                plugins: [
                    {
                        refreshFn: function(plugin) {
                            Ext.getStore('Rolls').sync();
                            Ext.getStore('Rolls').load();
                        },
                        type: 'pullrefresh'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                id: 'InventoryForm',
                defaults: {
                    labelWidth: '40%'
                },
                items: [
                    {
                        xtype: 'fieldset',
                        id: 'FilmFields',
                        defaults: {
                            labelWidth: '40%'
                        },
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'MnfField',
                                labelWrap: true,
                                name: 'Manufacturer',
                                autoComplete: true,
                                placeHolder: 'Manufacturer'
                            },
                            {
                                xtype: 'textfield',
                                id: 'TypeField',
                                name: 'Type',
                                autoComplete: true,
                                placeHolder: 'Type'
                            },
                            {
                                xtype: 'textfield',
                                id: 'ShadeField',
                                name: 'Shade',
                                autoComplete: true,
                                placeHolder: 'Shade'
                            },
                            {
                                xtype: 'textfield',
                                id: 'SizeField',
                                name: 'Size',
                                autoComplete: true,
                                placeHolder: 'Size'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        id: 'RollFields',
                        ui: 'dark',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'RollNumberField',
                                name: 'RollNumber',
                                autoComplete: false,
                                placeHolder: 'Roll Number'
                            },
                            {
                                xtype: 'textfield',
                                id: 'LinearFeetField',
                                name: 'LinearFeet',
                                placeHolder: 'Linear Feet'
                            },
                            {
                                xtype: 'textfield',
                                id: 'PriceField',
                                name: 'Price',
                                placeHolder: 'Price'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'InventoryEnter',
                        ui: 'action',
                        text: 'Add'
                    }
                ]
            }
        ]
    }

});