/*
 * File: app/view/Settings.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Settings', {
    extend: 'Ext.Container',
    alias: 'widget.settings',

    requires: [
        'MyApp.view.ioLoginbutton',
        'MyApp.view.override.Settings'
    ],

    config: {
        id: 'settings',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'formpanel',
                id: 'settingsForm',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'French Pane',
                        items: [
                            {
                                xtype: 'container',
                                layout: {
                                    type: 'fit'
                                },
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        placeHolder: 'Width'
                                    },
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        placeHolder: 'Height'
                                    },
                                    {
                                        xtype: 'spacer'
                                    },
                                    {
                                        xtype: 'numberfield',
                                        placeHolder: '$0.00'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Labor',
                        items: [
                            {
                                xtype: 'container',
                                items: [
                                    {
                                        xtype: 'numberfield',
                                        placeHolder: 'Cost per Sqft'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Sales Commision',
                        items: [
                            {
                                xtype: 'numberfield',
                                placeHolder: '%'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'Tax',
                        items: [
                            {
                                xtype: 'numberfield',
                                name: 'Tax',
                                placeHolder: '$0.00'
                            }
                        ]
                    },
                    {
                        xtype: 'sioAuthButton',
                        cls: 'btn',
                        height: 25,
                        text: 'Logout'
                    }
                ]
            }
        ]
    }

});