/*
 * File: app/view/Settings.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Settings', {
    extend: 'Ext.Container',
    alias: 'widget.settings',

    requires: [
        'MyApp.view.override.Settings'
    ],

    config: {
        id: 'settings',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'formpanel',
                items: [
                    {
                        xtype: 'fieldset',
                        title: 'French Panes',
                        items: [
                            {
                                xtype: 'numberfield',
                                label: 'Field'
                            },
                            {
                                xtype: 'numberfield',
                                label: 'French Pane'
                            },
                            {
                                xtype: 'sliderfield',
                                label: 'Field'
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        title: 'MyFieldSet7',
                        items: [
                            {
                                xtype: 'textfield',
                                label: 'Field'
                            },
                            {
                                xtype: 'textfield',
                                label: 'Field'
                            }
                        ]
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Field',
                        placeHolder: 'mm/dd/yyyy',
                        picker: {
                            itemId: 'mydatepicker'
                        }
                    },
                    {
                        xtype: 'numberfield',
                        label: 'Field'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMydatepickerPick',
                event: 'pick',
                delegate: '#mydatepicker'
            }
        ]
    },

    onMydatepickerPick: function(picker, value, slot, options) {
        console.log(value, slot);
    }

});