/*
 * File: app/model/Employee.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Employee', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'First',
                type: 'string'
            },
            {
                name: 'Last',
                type: 'string'
            },
            {
                name: 'Phone',
                type: 'string'
            },
            {
                name: 'Email',
                type: 'string'
            },
            {
                name: 'Street',
                type: 'string'
            },
            {
                name: 'City',
                type: 'string'
            },
            {
                name: 'State',
                type: 'string'
            },
            {
                name: 'Zip',
                type: 'int'
            },
            {
                name: 'Birthday',
                type: 'string'
            },
            {
                name: 'StartDate',
                type: 'date'
            },
            {
                name: 'Position',
                type: 'string'
            },
            {
                name: 'EmployeeId',
                type: 'int'
            },
            {
                name: 'PicUrl',
                type: 'string'
            }
        ],
        validations: [
            {
                type: 'presence',
                field: 'First'
            },
            {
                type: 'presence',
                field: 'Last'
            },
            {
                type: 'presence',
                field: 'Phone'
            },
            {
                type: 'presence',
                field: 'Email'
            },
            {
                type: 'presence',
                field: 'Street'
            },
            {
                type: 'presence',
                field: 'City'
            },
            {
                type: 'presence',
                field: 'State'
            },
            {
                type: 'presence',
                field: 'Zip'
            },
            {
                type: 'presence',
                field: 'Email'
            }
        ]
    }
});