/*
 * File: app/model/Order.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Order', {
    extend: 'Ext.data.Model',

    uses: [
        'MyApp.model.Window'
    ],

    config: {
        fields: [
            {
                name: 'Number'
            },
            {
                name: 'Status'
            },
            {
                name: 'Created'
            },
            {
                name: 'Updated'
            },
            {
                name: 'First'
            },
            {
                name: 'Last'
            },
            {
                name: 'Company'
            },
            {
                name: 'Phone'
            },
            {
                name: 'Email'
            },
            {
                name: 'Street'
            },
            {
                name: 'City'
            },
            {
                name: 'State'
            },
            {
                name: 'Zip'
            }
        ],
        hasMany: {
            model: 'MyApp.model.Window',
            autoLoad: true,
            autoSync: true,
            name: 'windows'
        }
    }
});