/*
 * File: app/model/Window.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Window', {
    extend: 'Ext.data.Model',
    alias: 'model.window',

    uses: [
        'MyApp.model.Window_has_Roll'
    ],

    config: {
        fields: [
            {
                name: 'Panes'
            },
            {
                name: 'Width'
            },
            {
                name: 'Height'
            },
            {
                name: 'Manufacturer'
            },
            {
                name: 'Type'
            },
            {
                name: 'Shade'
            },
            {
                name: 'Location'
            },
            {
                name: 'Direction'
            },
            {
                name: 'Removal'
            },
            {
                name: 'RollSize'
            },
            {
                name: 'LinearFeet'
            },
            {
                name: 'Cut'
            },
            {
                name: 'RollNumber'
            },
            {
                name: 'orderNumber'
            }
        ],
        hasMany: {
            model: 'MyApp.model.Window_has_Roll',
            autoLoad: true,
            autoSync: true,
            foreignKey: 'Window_id',
            name: 'whr'
        }
    }
});