// Generated by CoffeeScript 1.3.3
(function() {
  var changeNumbers, inner, outer, vaaa;

  outer = 1;

  changeNumbers = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  inner = changeNumbers();

  vaaa = "this";

}).call(this);
