/*
 * File: app/controller/Employee.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Employee', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            upfile: '#upfile',
            upfilebtn: '#upfilebtn',
            picform: '#picform',
            EmployeeForm: '#EmployeeForm',
            employees: '#employees'
        },

        control: {
            "#EnterEmployeeBtn": {
                tap: 'onEnterEmployeeBtnTap'
            },
            "#addEmployee": {
                tap: 'onAddEmployeeBtnTap'
            },
            "#closeEmployee": {
                tap: 'onCloseEmployeeBtnTap'
            },
            "button": {
                success: 'onButtonSuccess'
            }
        }
    },

    onEnterEmployeeBtnTap: function(button, e, eOpts) {
        var formData = this.getEmployeeForm().getValues();



        var model = Ext.create("MyApp.model.Employee", formData);
        var store = Ext.getStore("Employees");

        store.add(model);
        store.sync();

    },

    onAddEmployeeBtnTap: function(button, e, eOpts) {
        this.getEmployees().animateActiveItem(1, {type:'slide',direction:'up'});

        var bttn = Ext.getCmp('addEmployee');

        bttn.setIconCls('arrow_down');
        bttn.setItemId('closeEmployee');
        bttn.setId('closeEmployee');

        bttn.observableId = '#closeEmployee';

        console.log(this);

        //this.clearOrder();

        //this.newOrder();
    },

    onCloseEmployeeBtnTap: function(button, e, eOpts) {
        this.getEmployees().animateActiveItem(0, {type:'slide',direction:'down'});

        var bttn = Ext.getCmp('addEmployee')

        bttn.setIconCls('add');
        bttn.setItemId('addEmployee');
        bttn.setId('addEmployee');

        bttn.observableId = '#addEmployee';

        //this.clearOrder();
    },

    onButtonSuccess: function(button, response, tis, el) {
        console.log('controlelr success yo', button, response, tis, el);
    }

});