/*
 * File: app/controller/ioControl.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.ioControl', {
    extend: 'Ext.app.Controller',
    alias: 'controller.iocontrol',

    config: {
    },

    init: function(application) {
        this.getApplication().sio.on({
            authorized: this.onAuth,
            logout: this.onLogout,
            usermessage: this.onUserMessage,
            scope: this
        });
    },

    onAuth: function(user) {
        console.log("onAuth", user);
        this.syncStores();
        return true;
    },

    onLogout: function() {
        var store = Ext.getStore('todos');
        store.getProxy().clear();
        store.load();
        this.getAddButton().setDisabled(true);
        return true;
    },

    onUserMessage: function(sender, message) {
        console.log('sender', sender, 'message', message);
        this.syncStores();
        return true;
    },

    syncStores: function() {
        console.log('sync stores..');

        //sync and load all stores
        var rollStore = Ext.getStore('Rolls');
        var orderStore = Ext.getStore('Orders');
        var windowStore = Ext.getStore('Windows');
        var employeeStore = Ext.getStore('Employees');
        rollStore.sync();
        rollStore.load();
        orderStore.sync();
        orderStore.load();
        windowStore.sync();
        windowStore.sync();
        employeeStore.load();
        employeeStore.sync();
    },

    syncCallback: function() {
        console.log("broadcast update", arguments);
        this.getApplication().sio.getUser(function(user, error) {
            if (user) {
                console.log("user", user);
                user.send({
                    message: "updated"
                },
                function() {
                    console.log("send callback");
                }
                );
            }
        });
    }

});