/*
 * File: app/controller/Navigation.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Navigation', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            ".slidenavigationview": {
                select: 'onContainerActivate'
            }
        }
    },

    onContainerActivate: function(me, item) {
        if((item.items.items[1].id == 'orders') && (item.items.items[0].items.length == 2)){

            item.items.items[0].add({
                xtype:'spacer'
            });

            item.items.items[0].add({
                xtype: 'button',
                id: 'addOrder',
                iconCls: 'add',
                iconMask: true
            });
        }

        if((item.items.items[1].id == 'inventory') && (item.items.items[0].items.length == 2)){

            item.items.items[0].add({
                xtype:'spacer'
            });

            item.items.items[0].add({
                xtype: 'button',
                id: 'addInventory',
                iconCls: 'add',
                iconMask: true
            });
        }

    }

});