/*
 * File: app/controller/test.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.test', {
    extend: 'Ext.app.Controller',
    alias: 'controller.test',

    config: {
        control: {
            "#sio": {
                connected: 'connected',
                offline: 'offline',
                authorized: 'authorized'
            }
        }
    },

    connected: function() {
        console.log('connected');

        this.syncStores();
    },

    offline: function() {
        console.log('offline');
    },

    authorized: function(user) {
        console.log('authorized', user);

        this.syncStores();
    },

    syncStores: function() {
        console.log('sync stores..');

        //sync and load all stores
        var rollStore = Ext.getStore('Rolls');
        var orderStore = Ext.getStore('Orders');
        rollStore.sync();
        orderStore.sync();
        rollStore.load();
        orderStore.load();
    }

});