/*
 * File: app/view/actionbutton.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.actionbutton', {
    extend: 'Ext.Button',
    alias: 'widget.actionbutton',

    config: {
        height: 20,
        ui: 'action',
        width: 35,
        iconCls: 'action',
        iconMask: true
    }

});