/*
 * File: app/view/Inventory.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Inventory', {
    extend: 'Ext.Container',
    alias: 'widget.inventory',

    config: {
        id: 'inventory',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'list',
                id: 'InventoryList',
                itemCls: 'tweet',
                itemTpl: [
                    '<div>{Manufacturer} {Type} {Shade}{Size}{RollNumber}{LinearFeet} </div>'
                ],
                store: 'Rolls',
                onItemDisclosure: true
            },
            {
                xtype: 'formpanel',
                id: 'InventoryForm',
                defaults: {
                    labelWidth: '40%'
                },
                items: [
                    {
                        xtype: 'fieldset',
                        id: 'FilmFields',
                        defaults: {
                            labelWidth: '40%'
                        },
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'MnfField',
                                label: 'Manufacturer',
                                labelWrap: true,
                                name: 'Manufacturer',
                                autoComplete: true
                            },
                            {
                                xtype: 'textfield',
                                id: 'TypeField',
                                label: 'Type',
                                name: 'Type',
                                autoComplete: true
                            },
                            {
                                xtype: 'textfield',
                                id: 'ShadeField',
                                label: 'Shade',
                                name: 'Shade',
                                autoComplete: true
                            },
                            {
                                xtype: 'textfield',
                                id: 'SizeField',
                                label: 'Size',
                                name: 'Size',
                                autoComplete: true
                            }
                        ]
                    },
                    {
                        xtype: 'fieldset',
                        id: 'RollFields',
                        defaults: {
                            labelWidth: '40%'
                        },
                        title: '',
                        items: [
                            {
                                xtype: 'textfield',
                                id: 'RollNumberField',
                                label: 'Roll Number',
                                name: 'RollNumber',
                                autoComplete: false
                            },
                            {
                                xtype: 'textfield',
                                id: 'LinearFeetField',
                                label: 'Linear Feet',
                                name: 'LinearFeet'
                            },
                            {
                                xtype: 'textfield',
                                id: 'PriceField',
                                label: 'Price',
                                name: 'Price'
                            }
                        ]
                    },
                    {
                        xtype: 'button',
                        id: 'InventoryEnter',
                        iconMask: true,
                        text: 'Enter'
                    }
                ]
            }
        ]
    }

});