/*
 * File: app/view/Orders.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Orders', {
    extend: 'Ext.Container',
    alias: 'widget.orders',

    requires: [
        'MyApp.view.MySegmentedButton1'
    ],

    config: {
        id: 'orders',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'list',
                id: 'OrderList',
                layout: {
                    type: 'fit'
                },
                itemTpl: [
                    '<div>Order {Number} was created on {Created}</div>'
                ],
                store: 'Orders',
                onItemDisclosure: true
            },
            {
                xtype: 'tabpanel',
                id: 'newOrder',
                itemId: 'newOrder',
                layout: {
                    animation: 'slide',
                    type: 'card'
                },
                tabBar: {
                    docked: 'bottom',
                    layout: {
                        pack: 'center',
                        type: 'hbox'
                    }
                },
                items: [
                    {
                        xtype: 'formpanel',
                        title: 'Add Windows',
                        iconCls: 'add',
                        id: 'AddWindowPanel',
                        items: [
                            {
                                xtype: 'fieldset',
                                id: 'WindowDemensions',
                                items: [
                                    {
                                        xtype: 'container',
                                        id: 'DimensionsPanel',
                                        layout: {
                                            align: 'center',
                                            pack: 'center',
                                            type: 'hbox'
                                        },
                                        items: [
                                            {
                                                xtype: 'numberfield',
                                                flex: 3,
                                                id: 'PanesField',
                                                width: '30px',
                                                name: 'Panes',
                                                placeHolder: 'Panes'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                flex: 3,
                                                id: 'WidthField',
                                                name: 'Width',
                                                placeHolder: 'Width'
                                            },
                                            {
                                                xtype: 'numberfield',
                                                flex: 3,
                                                id: 'HeightField',
                                                name: 'Height',
                                                placeHolder: 'Height'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                id: 'WindowDetails',
                                defaults: {
                                    labelWidth: '30%'
                                },
                                items: [
                                    {
                                        xtype: 'selectfield',
                                        id: 'FilmSelect',
                                        label: 'Film',
                                        listeners: [
                                            {
                                                fn: function(component, options) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t){this.fireEvent('tap', this, e, t);}, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Location',
                                        label: 'Location',
                                        name: 'Location'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        id: 'Direction',
                                        label: 'Direction',
                                        name: 'Direction',
                                        options: [
                                            {
                                                text: '',
                                                value: ''
                                            },
                                            {
                                                text: 'North',
                                                value: 'North'
                                            },
                                            {
                                                text: 'South',
                                                value: 'South'
                                            },
                                            {
                                                text: 'East',
                                                value: 'East'
                                            },
                                            {
                                                text: 'West',
                                                value: 'West'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'sliderfield',
                                        id: 'Difficulty',
                                        label: 'Removal',
                                        name: 'Difficulty',
                                        maxValue: 10
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'hMnfField',
                                        name: 'Manufacturer'
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'hTypeField',
                                        name: 'Type'
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'hShadeField',
                                        name: 'Shade'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                id: 'enterOrder',
                                iconMask: true,
                                text: 'Enter'
                            }
                        ]
                    },
                    {
                        xtype: 'formpanel',
                        title: 'Customer',
                        iconCls: 'user',
                        id: 'CustomerPanel',
                        scrollable: true,
                        items: [
                            {
                                xtype: 'fieldset',
                                id: 'contact',
                                title: 'Contact',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        cls: [
                                            'hddn'
                                        ],
                                        id: 'First',
                                        label: 'First',
                                        name: 'First'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: [
                                            'h'
                                        ],
                                        id: 'Last',
                                        inputCls: 'hcustomer',
                                        label: 'Last',
                                        name: 'Last'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Phone',
                                        inputCls: 'hcustomer',
                                        label: 'Phone',
                                        name: 'Phone'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Email',
                                        inputCls: 'hcustomer',
                                        label: 'Email',
                                        name: 'Email'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Company',
                                        inputCls: 'hcustomer',
                                        label: 'Company',
                                        name: 'Company'
                                    }
                                ]
                            },
                            {
                                xtype: 'fieldset',
                                id: 'Address',
                                layout: {
                                    type: 'default'
                                },
                                title: 'Job Address',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'Street',
                                        label: 'Street',
                                        name: 'Street'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'City',
                                        label: 'City',
                                        name: 'City'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'State',
                                        label: 'State',
                                        name: 'State'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Zip',
                                        label: 'Zip',
                                        name: 'Zip'
                                    },
                                    {
                                        xtype: 'checkboxfield',
                                        id: 'BillingAddressOption',
                                        label: 'Billing Address (if different)',
                                        labelWidth: '75%'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        title: 'Windows',
                        iconCls: 'info',
                        cls: [
                            'windowlist-wrapper'
                        ],
                        id: 'WindowList',
                        styleHtmlContent: true,
                        itemCls: 'windowlist-wrapper',
                        itemTpl: [
                            '<div class="tweet"><h2>{Location}</h2><p>{Panes} - {Width} X {Height}   {Cut} cut from a {RollSize}" {Type} linearfeet {LinearFeet}</p></div>'
                        ],
                        itemHeight: 30,
                        onItemDisclosure: true
                    },
                    {
                        xtype: 'list',
                        title: 'MyList3',
                        iconCls: 'info',
                        id: 'TotalList',
                        styleHtmlContent: true,
                        itemTpl: [
                            '<div>List Item {LinearFeet}</div>'
                        ],
                        store: 'Windows_has_Rolls',
                        disableSelection: true,
                        grouped: true,
                        itemHeight: 35
                    },
                    {
                        xtype: 'panel',
                        title: 'MyPanel',
                        iconCls: 'info',
                        items: [
                            {
                                xtype: 'mysegmentedbutton1'
                            }
                        ]
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onNewOrderActivate',
                event: 'activate',
                delegate: '#newOrder'
            }
        ]
    },

    onNewOrderActivate: function(container, newActiveItem, oldActiveItem, options) {
        var tp = Ext.getCmp('newOrder');

        var btn = Ext.create('widget.actionbutton', {
            id: 'actionBttn',
            style:'position:absolute;top:auto;bottom:10px;right:10px;z-index:10;'

        });

        tp.element.insertFirst(btn.element);
    }

});